# Generated by Django 3.1.5 on 2021-03-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210304_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdffile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='pdffor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='format',
        ),
        migrations.AlterField(
            model_name='vetan5680',
            name='dob',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='linkto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pdffor'),
        ),
    ]
