# Generated by Django 3.1.5 on 2021-03-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210305_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetan5680',
            name='range',
        ),
    ]
