# Generated by Django 3.1.5 on 2021-03-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_vetan5680_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetan5680',
            name='division',
        ),
    ]
