# Generated by Django 3.1.5 on 2021-03-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_vetan5680_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetan5680',
            name='division',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vetan5680',
            name='range',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
