# Generated by Django 3.1.5 on 2021-03-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210305_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetan5680',
            name='division',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vetan5680',
            name='range',
            field=models.CharField(max_length=50),
        ),
    ]
