# Generated by Django 3.1.5 on 2021-03-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210305_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetan5680',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.division'),
        ),
    ]
