# Generated by Django 3.1.5 on 2021-03-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210311_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
