# Generated by Django 3.1.5 on 2021-03-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210311_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdffile',
            old_name='subject',
            new_name='javak',
        ),
    ]
