# Generated by Django 3.1.5 on 2021-03-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210311_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
