# Generated by Django 3.1.5 on 2021-03-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210311_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='date',
        ),
    ]
